---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: octank-invogue
  namespace: test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: octank-invogue
    spec:
      containers:
      - name: octank-invogue
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        # image: REGISTRY/REPO:TAG
        # The full image will be dynamically added by Kustomize in the workflow.
        image: example-eks
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
